from . import stock_location
from . import product_category
from . import product_template
from . import mig_materialesarticulo
from . import mig_articuloidioma
from . import mig_componentes
from . import mig_embalaje
from . import res_partner
from . import mig_lineastarifa
from . import product_pricelist
from . import hr_employee
from . import sale_order
from . import sale_order_line
